import {
  ArrowRight,
  Activity,
  BadgeCheck,
  Bell,
  Bookmark,
  BookOpen,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  CalendarRange,
  ChartColumn,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleDot,
  Clock,
  CreditCard,
  Dumbbell,
  Ellipsis,
  Eye,
  EyeOff,
  Feather,
  Filter,
  GraduationCap,
  Grid2x2,
  Grip,
  House,
  Info,
  Layers,
  LayoutDashboard,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Menu,
  PanelLeft,
  Plus,
  Receipt,
  Scan,
  Search,
  Settings,
  Shield,
  Sparkles,
  SquareDashed,
  Star,
  Sun,
  Tag,
  TrendingUp,
  TriangleAlert,
  Trophy,
  User,
  Users,
  Wallet,
  X,
  Zap,
} from "lucide-react";
import { cn } from "@/lib/utils/cn";

/** Central icon registry — maps kebab keys (nav/config) to lucide components. */
export const ICONS = {
  "layout-dashboard": LayoutDashboard,
  "calendar-plus": CalendarPlus,
  "calendar-check": CalendarCheck,
  "calendar-range": CalendarRange,
  "badge-check": BadgeCheck,
  "credit-card": CreditCard,
  "grid-2x2": Grid2x2,
  "bar-chart-3": ChartColumn,
  "book-open": BookOpen,
  "map-pin": MapPin,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "panel-left": PanelLeft,
  "log-out": LogOut,
  "arrow-right": ArrowRight,
  "trending-up": TrendingUp,
  "circle-dot": CircleDot,
  "square-dashed": SquareDashed,
  "check-circle": CheckCircle,
  "circle-alert": CircleAlert,
  "triangle-alert": TriangleAlert,
  bell: Bell,
  user: User,
  users: Users,
  settings: Settings,
  trophy: Trophy,
  layers: Layers,
  receipt: Receipt,
  home: House,
  sparkles: Sparkles,
  tag: Tag,
  star: Star,
  mail: Mail,
  search: Search,
  menu: Menu,
  x: X,
  plus: Plus,
  check: Check,
  clock: Clock,
  filter: Filter,
  ellipsis: Ellipsis,
  eye: Eye,
  "eye-off": EyeOff,
  sun: Sun,
  calendar: Calendar,
  whistle: GraduationCap,
  "graduation-cap": GraduationCap,
  grip: Grip,
  feather: Feather,
  scan: Scan,
  dumbbell: Dumbbell,
  zap: Zap,
  shield: Shield,
  wallet: Wallet,
  activity: Activity,
  bookmark: Bookmark,
  info: Info,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
  size,
  strokeWidth = 2,
  style,
}: {
  name: IconName | string;
  className?: string;
  size?: number;
  strokeWidth?: number;
  style?: React.CSSProperties;
}) {
  const Cmp = ICONS[name as IconName] ?? CircleDot;
  return <Cmp className={cn("shrink-0", className)} size={size} strokeWidth={strokeWidth} style={style} />;
}
