import {
  Archive,
  ArrowRight,
  Activity,
  BadgeCheck,
  Banknote,
  Barcode,
  Bell,
  Bookmark,
  BookOpen,
  Boxes,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  CalendarRange,
  ChartColumn,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleDollarSign,
  CircleDot,
  Clock,
  Coins,
  ConciergeBell,
  Cookie,
  CreditCard,
  CupSoda,
  Dumbbell,
  Ellipsis,
  Eye,
  EyeOff,
  Feather,
  Filter,
  Gift,
  GraduationCap,
  Gauge,
  Grid2x2,
  Grip,
  Heart,
  Hourglass,
  House,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  Minus,
  Moon,
  Package,
  PackageCheck,
  PackageOpen,
  PanelLeft,
  Pencil,
  Percent,
  Plus,
  Printer,
  Receipt,
  RotateCcw,
  Scan,
  Search,
  Settings,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Sparkles,
  Square,
  SquareDashed,
  Star,
  Store,
  Sun,
  Tag,
  Ticket,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  User,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  X,
  Zap,
} from "lucide-react";
import { cn } from "@/lib/utils/cn";

/** Central icon registry — maps kebab keys (nav/config) to lucide components. */
export const ICONS = {
  "layout-dashboard": LayoutDashboard,
  "calendar-plus": CalendarPlus,
  "calendar-check": CalendarCheck,
  "calendar-range": CalendarRange,
  "badge-check": BadgeCheck,
  "credit-card": CreditCard,
  "grid-2x2": Grid2x2,
  "layout-grid": LayoutGrid,
  maximize: Maximize2,
  gauge: Gauge,
  square: Square,
  "bar-chart-3": ChartColumn,
  "book-open": BookOpen,
  "map-pin": MapPin,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "panel-left": PanelLeft,
  "log-out": LogOut,
  "arrow-right": ArrowRight,
  "trending-up": TrendingUp,
  "circle-dot": CircleDot,
  "square-dashed": SquareDashed,
  "check-circle": CheckCircle,
  "circle-alert": CircleAlert,
  "triangle-alert": TriangleAlert,
  bell: Bell,
  user: User,
  users: Users,
  settings: Settings,
  trophy: Trophy,
  layers: Layers,
  receipt: Receipt,
  home: House,
  sparkles: Sparkles,
  tag: Tag,
  star: Star,
  mail: Mail,
  search: Search,
  menu: Menu,
  x: X,
  plus: Plus,
  check: Check,
  clock: Clock,
  filter: Filter,
  ellipsis: Ellipsis,
  eye: Eye,
  "eye-off": EyeOff,
  sun: Sun,
  moon: Moon,
  calendar: Calendar,
  whistle: GraduationCap,
  "graduation-cap": GraduationCap,
  grip: Grip,
  feather: Feather,
  scan: Scan,
  dumbbell: Dumbbell,
  zap: Zap,
  shield: Shield,
  wallet: Wallet,
  activity: Activity,
  bookmark: Bookmark,
  info: Info,
  // POS module
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  package: Package,
  "package-open": PackageOpen,
  "package-check": PackageCheck,
  "concierge-bell": ConciergeBell,
  hourglass: Hourglass,
  "rotate-ccw": RotateCcw,
  heart: Heart,
  boxes: Boxes,
  warehouse: Warehouse,
  barcode: Barcode,
  banknote: Banknote,
  coins: Coins,
  "circle-dollar-sign": CircleDollarSign,
  percent: Percent,
  printer: Printer,
  minus: Minus,
  "trash-2": Trash2,
  trash: Trash2,
  shirt: Shirt,
  cookie: Cookie,
  "cup-soda": CupSoda,
  ticket: Ticket,
  gift: Gift,
  store: Store,
  pencil: Pencil,
  archive: Archive,
  "user-plus": UserPlus,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
  size,
  strokeWidth = 2,
  style,
}: {
  name: IconName | string;
  className?: string;
  size?: number;
  strokeWidth?: number;
  style?: React.CSSProperties;
}) {
  const Cmp = ICONS[name as IconName] ?? CircleDot;
  return <Cmp className={cn("shrink-0", className)} size={size} strokeWidth={strokeWidth} style={style} />;
}
